import type { IPlaylist } from "@/types/types";

const playlistsData: IPlaylist[] = [
  {
    id: 54,
    name: "Drum & Bass On The Bike - FRANKFURT",
    country: "Germany",
    city: "Frankfurt",
    year: 2024,
    date: "19.7.2024",
    videoId: "K0pdUFP84Jk",
    url: "https://www.youtube-nocookie.com/watch?v=K0pdUFP84Jk",
    latest: true,
    items: [
      {
        time: 0,
        title: "Benson Boone - Slow It Down (DRZ EDIT)",
        url: "",
      },
      { time: 192, title: "Crystal Clear - Serious Sound", url: "" },
      { time: 406, title: "Selecta J-Man - Cry no more", url: "" },
      { time: 619, title: "RJD X G-Class X Darko - Boom Selekky", url: "" },
      { time: 918, title: "Deep Notion - Something About You", url: "" },
      { time: 1045, title: "DRS - I Will ft Patife & Vangeliez", url: "" },
      { time: 1216, title: "Daft Punk - One More Time (??? Remix)", url: "" },
      { time: 1304, title: "SpectraSoul - Second Chance", url: "" },
      {
        time: 1400,
        title: "Serial Killaz - Lovely Woman (??? Remix)",
        url: "",
      },
      { time: 1528, title: "Unknown", url: "" },
      {
        time: 1608,
        title: "RJD X G-Class X Darko - Boom Selekky INTRO",
        url: "",
      },
      { time: 1652, title: "Unknown", url: "" },
      {
        time: 1750,
        title: "Formula & Drowzee - PA Systematic (Bennie Remix)",
        url: "",
      },
      { time: 1902, title: "Aries - Not so bad", url: "" },
      { time: 2051, title: "Crystal Clear - Madhouse", url: "" },
      {
        time: 2200,
        title: "Damian Marley - Welcome to Jamrock(London) ???",
        url: "",
      },
      {
        time: 2340,
        title: "Pola & Bryson, DJ Marky & IYAMAH - Be There",
        url: "",
      },
      { time: 2538, title: "Crystal Clear - Star Studded", url: "" },
      { time: 2649, title: "Selecta J-Man - Dance With Me", url: "" },
      { time: 2883, title: "???", url: "" },
      {
        time: 3010,
        title: "Spice - So Mi Like It (BURT COPE BOOTLEG) VIP",
        url: "",
      },
      { time: 3117, title: "Serum & Voltage - Mission Control", url: "" },
      { time: 3202, title: "Juice Wrld - Be Fine (Upgrade Bootleg)", url: "" },
      {
        time: 3395,
        title: "Route 94 - My Love (feat. Jess Glynne) [Sigma Remix]",
        url: "",
      },
      { time: 3460, title: "Sub Zero & Majistrate - Zero Tolerance", url: "" },
      {
        time: 3670,
        title: "Eliza Rose - B.O.T.A - Muted Hue Bootleg",
        url: "",
      },
      { time: 3790, title: "Aries - Herbsmoke (Visionary Remix)", url: "" },
      { time: 3864, title: "Formula & Jenks - Cash Grab", url: "" },
      {
        time: 3950,
        title: "Benny Benassi - Satisfaction (FORBIDDEN Edit)",
        url: "",
      },
      { time: 4111, title: "Selecta J-Man & Kiko Bun - Not Me", url: "" },
      { time: 4255, title: "Formula - Vowels", url: "" },
      {
        time: 4361,
        title: "Wilkinson - Take You Higher blended with unknown",
        url: "",
      },
      { time: 4519, title: "Formula, Jamezy, 4K - Puss In Boots", url: "" },
      {
        time: 4691,
        title: "Selecta J-Man & MC Spyda - No Sound Can Test",
        url: "",
      },
      { time: 4775, title: "Chase & Status - No Problem", url: "" },
      { time: 4821, title: "Prodigy - Voodoo People Delta Heavy", url: "" },
      { time: 4946, title: "Formula - So Lost (Formula Remix)", url: "" },
      {
        time: 5183,
        title: "The Drop - Looking To The Sky (Aries & Kelvin 373 Remix)",
        url: "",
      },
      { time: 5311, title: "Sikoti - Say It Right", url: "" },
      { time: 5423, title: "Deep Notion - Hands Up", url: "" },
      { time: 5530, title: "Selecta J-Man - OG Rudeboy", url: "" },
      { time: 5743, title: "Hedex - No More Fighting", url: "" },
    ],
  },
  {
    id: 53,
    name: "Drum & Bass On The Bike - SWITZERLAND",
    city: "Zurich",
    country: "Switzerland",
    year: 2024,
    date: "13.6.2024",
    videoId: "V_ERm18dBCY",
    url: "https://www.youtube-nocookie.com/watch?v=V_ERm18dBCY",
    latest: false,
    items: [
      {
        time: 0,
        title: "Formula - Bratt Selection",
        url: "https://youtu.be/p-G0g-dNIzo",
      },
      { time: 233, title: "???", url: "" },
      {
        time: 468,
        title: "Version - Gimmicks",
        url: "https://youtu.be/IOYMzRrjd3s",
      },
      {
        time: 638,
        title: "???",
        url: "",
      },
      {
        time: 851,
        title: "Decades & Mansa - Gin & Tonic (Same sample unknown remix)",
        url: "",
      },
      {
        time: 1064,
        title: "TZ- Reminisce",
        url: "https://youtu.be/a8qYMbRaJek",
      },
      {
        time: 1256,
        title: "HERMIT - Break It Off (KIPPO Remix)",
        url: "https://youtu.be/8QBrCIR4MPc",
      },
      {
        time: 1432,
        title: "DRZ - Reasons",
        url: "https://youtu.be/4OfzB2NvucU",
      },
      {
        time: 1602,
        title: "Dawn wall - Fears",
        url: "https://youtu.be/TRLrEpcnWh0",
      },
      {
        time: 1752,
        title: "Britney Spears - Toxic (Formula Remix)",
        url: "https://youtu.be/A1aRxotJu8M",
      },
      {
        time: 1857,
        title: "Break the silence ???",
        url: "",
      },
      {
        time: 2050,
        title: "Tantrum Desire - Reach (??? Remix)",
        url: "",
      },
      {
        time: 2135,
        title:
          "TC - Next Hype (ft. Jakes) (Crissy Criss + Malux + Erb N Dub Remix)",
        url: "https://youtu.be/6ndeBQg2Yes",
      },
      {
        time: 2199,
        title: "???",
        url: "https://youtu.be/6ndeBQg2Yes",
      },
      {
        time: 2305,
        title: "Route 94 - My Love (Ft. Jess Glynne) (Sigma Remix)",
        url: "https://youtu.be/NCM0LqEOdbU",
      },
      {
        time: 2391,
        title: "Majistrate - Bombaclart (Turno Remix)",
        url: "https://youtu.be/ZLvo6eTvDgg",
      },
      {
        time: 2495,
        title: "TZ - Show me",
        url: "https://youtu.be/ZCzX7CxuYos",
      },
      {
        time: 2709,
        title: "???",
        url: "",
      },
      {
        time: 2950,
        title: "Fall In Love (Dope Ammo & Marvellous Cain Remix)",
        url: "https://youtu.be/EGF_2f5lqxY",
      },
      {
        time: 3152,
        title: "Formula - Warrior VIP Remix)",
        url: "https://youtu.be/-7M5xG6WJBk",
      },
      {
        time: 3365,
        title: "Childish Gambino - Redbone (??? Remix)",
        url: "",
      },
      {
        time: 3514,
        title: "???",
        url: "",
      },
      {
        time: 3621,
        title: "???",
        url: "",
      },
      {
        time: 3748,
        title: "Ashanti - Unfoolish (??? Remix)",
        url: "",
      },
      {
        time: 3898,
        title: "???",
        url: "",
      },
    ],
  },
  {
    id: 52,
    name: "Drum & Bass On The Bike - DARWIN",
    city: "Darwin",
    country: "Australia",
    year: 2024,
    date: "27.5.2024",
    videoId: "SZGyi9km_6E",
    url: "https://www.youtube-nocookie.com/watch?v=SZGyi9km_6E",
    latest: false,
    items: [{ time: 0, title: "Work in progress", url: "" }],
  },
  {
    id: 51,
    name: "Drum & Bass On The Bike - BRISTOL",
    city: "Bristol",
    country: "England",
    year: 2024,
    date: "4.4.2024",
    videoId: "RqimBw6uTWg",
    url: "https://www.youtube-nocookie.com/watch?v=RqimBw6uTWg",
    latest: false,
    items: [{ time: 0, title: "Work in progress", url: "" }],
  },
  {
    id: 50,
    name: "Drum & Bass On The Bike - SOUTHAMPTON",
    city: "Southampton",
    country: "England",
    year: 2024,
    date: "7.3.2024",
    videoId: "shzJxoNBF5M",
    url: "https://youtube-nocookie.com/watch?v=shzJxoNBF5M",
    latest: false,
    items: [{ time: 0, title: "Work in progress", url: "" }],
  },
];

export default playlistsData;
